---
version: "2.0"

services:
  app:
    image: ubuntu:latest     
    
    command:
      - "bash"
      - "-c"
    args:
      - 'apt-get update ;
        apt-get upgrade -y ;
        apt-get install -y  ssh goxkcdpwgen ;
        PASS=$(goxkcdpwgen -n 2 -c -d "-");
        echo "PermitRootLogin yes" >> /etc/ssh/sshd_config ;
        "(echo $PASS; echo $PASS)" | passwd root ;
        service ssh start;
        echo "==== ssh user: root ===" ;
        echo "=== ssh pass: $PASS ===" ;
        sleep infinity'
    
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true 
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 4Gi
        storage:
          size: 50Gi
         
  placement:
    akash: 
      attributes:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
